(function(i){var f={undHash:/_|-/,colons:/::/,words:/([A-Z]+)([A-Z][a-z])/g,lowUp:/([a-z\d])([A-Z])/g,dash:/([a-z\d])([A-Z])/g,replacer:/\{([^\}]+)\}/g,dot:/\./},k=function(a,b,c){return a[b]!==undefined?a[b]:c&&(a[b]={})},l=function(a){return(a=typeof a)&&(a=="function"||a=="object")},m=function(a,b,c){a=a?a.split(f.dot):[];var g=a.length;b=i.isArray(b)?b:[b||window];var d,e,h,n=0;if(g==0)return b[0];for(;d=b[n++];){for(h=0;h<g-1&&l(d);h++)d=k(d,a[h],c);if(l(d)){e=k(d,a[h],c);if(e!==undefined){c===
false&&delete d[a[h]];return e}}}},j=i.String=i.extend(i.String||{},{getObject:m,capitalize:function(a){return a.charAt(0).toUpperCase()+a.substr(1)},camelize:function(a){a=j.classize(a);return a.charAt(0).toLowerCase()+a.substr(1)},classize:function(a,b){a=a.split(f.undHash);for(var c=0;c<a.length;c++)a[c]=j.capitalize(a[c]);return a.join(b||"")},niceName:function(a){return j.classize(a," ")},underscore:function(a){return a.replace(f.colons,"/").replace(f.words,"$1_$2").replace(f.lowUp,"$1_$2").replace(f.dash,
"_").toLowerCase()},sub:function(a,b,c){var g=[];g.push(a.replace(f.replacer,function(d,e){d=m(e,b,typeof c=="boolean"?!c:c);e=typeof d;if((e==="object"||e==="function")&&e!==null){g.push(d);return""}else return""+d}));return g.length<=1?g[0]:g},_regs:f})})(jQuery);
(function(i){var j=false,o=i.makeArray,p=i.isFunction,l=i.isArray,m=i.extend,s=i.String.getObject,q=function(a,c){return a.concat(o(c))},t=/xyz/.test(function(){})?/\b_super\b/:/.*/,r=function(a,c,d){d=d||a;for(var b in a)d[b]=p(a[b])&&p(c[b])&&t.test(a[b])?function(g,h){return function(){var f=this._super,e;this._super=c[g];e=h.apply(this,arguments);this._super=f;return e}}(b,a[b]):a[b]};clss=i.Class=function(){arguments.length&&clss.extend.apply(clss,arguments)};m(clss,{proxy:function(a){var c=
o(arguments),d;a=c.shift();l(a)||(a=[a]);d=this;return function(){for(var b=q(c,arguments),g,h=a.length,f=0,e;f<h;f++)if(e=a[f]){if((g=typeof e=="string")&&d._set_called)d.called=e;b=(g?d[e]:e).apply(d,b||[]);if(f<h-1)b=!l(b)||b._use_call?[b]:b}return b}},newInstance:function(){var a=this.rawInstance(),c;if(a.setup)c=a.setup.apply(a,arguments);if(a.init)a.init.apply(a,l(c)?c:arguments);return a},setup:function(a){this.defaults=m(true,{},a.defaults,this.defaults);return arguments},rawInstance:function(){j=
true;var a=new this;j=false;return a},extend:function(a,c,d){function b(){if(!j)return this.constructor!==b&&arguments.length?arguments.callee.extend.apply(arguments.callee,arguments):this.Class.newInstance.apply(this.Class,arguments)}if(typeof a!="string"){d=c;c=a;a=null}if(!d){d=c;c=null}d=d||{};var g=this,h=this.prototype,f,e,k,n;j=true;n=new this;j=false;r(d,h,n);for(f in this)if(this.hasOwnProperty(f))b[f]=this[f];r(c,this,b);if(a){k=a.split(/\./);e=k.pop();k=h=s(k.join("."),window,true);h[e]=
b}m(b,{prototype:n,namespace:k,shortName:e,constructor:b,fullName:a});b.prototype.Class=b.prototype.constructor=b;g=b.setup.apply(b,q([g],arguments));if(b.init)b.init.apply(b,g||[]);return b}});clss.callback=clss.prototype.callback=clss.prototype.proxy=clss.proxy})(jQuery);

(function(a){var e=jQuery.cleanData;a.cleanData=function(b){for(var c=0,d;(d=b[c])!==undefined;c++)a(d).triggerHandler("destroyed");e(b)}})(jQuery);
(function(e){var v=function(a,b,c){var d,f=a.bind&&a.unbind?a:e(j(a)?[a]:a);if(b.indexOf(">")===0){b=b.substr(1);d=function(i){i.target===a&&c.apply(this,arguments)}}f.bind(b,d||c);return function(){f.unbind(b,d||c);a=b=c=d=null}},p=e.makeArray,w=e.isArray,j=e.isFunction,k=e.extend,q=e.String,r=e.each,x=Array.prototype.slice,y=function(a,b,c,d){var f=a.delegate&&a.undelegate?a:e(j(a)?[a]:a);f.delegate(b,c,d);return function(){f.undelegate(b,c,d);f=a=c=d=b=null}},s=function(a,b,c,d){return d?y(a,d,
b,c):v(a,b,c)},l=function(a,b){var c=typeof b=="string"?a[b]:b;return function(){a.called=b;return c.apply(a,[this.nodeName?e(this):this].concat(x.call(arguments,0)))}},z=/\./g,A=/_?controllers?/ig,t=function(a){return q.underscore(a.replace("jQuery.","").replace(z,"_").replace(A,""))},B=/[^\w]/,u=/\{([^\}]+)\}/g,C=/^(?:(.*?)\s)?([\w\.\:>]+)$/,m,n=function(a,b){return e.data(a,"controllers",b)};e.Class("jQuery.Controller",{setup:function(){this._super.apply(this,arguments);if(!(!this.shortName||this.fullName==
"jQuery.Controller")){this._fullName=t(this.fullName);this._shortName=t(this.shortName);var a=this,b=this.pluginName||this._fullName,c;e.fn[b]||(e.fn[b]=function(d){var f=p(arguments),i=typeof d=="string"&&j(a.prototype[d]),D=f[0];return this.each(function(){var g=n(this);if(g=g&&g[b])i?g[D].apply(g,f.slice(1)):g.update.apply(g,f);else a.newInstance.apply(a,[this].concat(f))})});this.actions={};for(c in this.prototype)if(!(c=="constructor"||!j(this.prototype[c])))if(this._isAction(c))this.actions[c]=
this._action(c)}},hookup:function(a){return new this(a)},_isAction:function(a){return B.test(a)?true:e.inArray(a,this.listensTo)>-1||e.event.special[a]||o[a]},_action:function(a,b){u.lastIndex=0;if(!b&&u.test(a))return null;a=b?q.sub(a,[b,window]):a;b=w(a);var c=(b?a[1]:a).match(C);return{processor:o[c[2]]||m,parts:c,delegate:b?a[0]:undefined}},processors:{},listensTo:[],defaults:{}},{setup:function(a,b){var c=this.constructor;a=a.jquery?a[0]:a;var d=c.pluginName||c._fullName;this.element=e(a).addClass(d);
(n(a)||n(a,{}))[d]=this;this.options=k(k(true,{},c.defaults),b);this.called="init";this.bind();return this.element},bind:function(a,b,c){if(a===undefined){this._bindings=[];a=this.constructor;b=this._bindings;c=a.actions;var d=this.element;for(funcName in c)if(c.hasOwnProperty(funcName)){ready=c[funcName]||a._action(funcName,this.options);b.push(ready.processor(ready.delegate||d,ready.parts[2],ready.parts[1],funcName,this))}var f=l(this,"destroy");d.bind("destroyed",f);b.push(function(i){e(i).unbind("destroyed",
f)});return b.length}if(typeof a=="string"){c=b;b=a;a=this.element}return this._binder(a,b,c)},_binder:function(a,b,c,d){if(typeof c=="string")c=l(this,c);this._bindings.push(s(a,b,c,d));return this._bindings.length},_unbind:function(){var a=this.element[0];r(this._bindings,function(b,c){c(a)});this._bindings=[]},delegate:function(a,b,c,d){if(typeof a=="string"){d=c;c=b;b=a;a=this.element}return this._binder(a,c,d,b)},update:function(a){k(this.options,a);this._unbind();this.bind()},destroy:function(){if(this._destroyed)throw this.constructor.shortName+
" controller already deleted";var a=this.constructor.pluginName||this.constructor._fullName;this._destroyed=true;this.element.removeClass(a);this._unbind();delete this._actions;delete this.element.data("controllers")[a];e(this).triggerHandler("destroyed");this.element=null},find:function(a){return this.element.find(a)},_set_called:true});var o=e.Controller.processors;m=function(a,b,c,d,f){return s(a,b,l(f,d),c)};r("change click contextmenu dblclick keydown keyup keypress mousedown mousemove mouseout mouseover mouseup reset resize scroll select submit focusin focusout mouseenter mouseleave".split(" "),
function(a,b){o[b]=m});var h,E=function(a,b){for(h=0;h<b.length;h++)if(typeof b[h]=="string"?a.constructor._shortName==b[h]:a instanceof b[h])return true;return false};e.fn.extend({controllers:function(){var a=p(arguments),b=[],c,d,f;this.each(function(){c=e.data(this,"controllers");for(f in c)if(c.hasOwnProperty(f)){d=c[f];if(!a.length||E(d,a))b.push(d)}});return b},controller:function(){return this.controllers.apply(this,arguments)[0]}})})(jQuery);
(function(){var n=$.String.underscore,z=$.String.classize,s=$.isArray,u=$.makeArray,t=$.extend,j=$.each,A=/GET|POST|PUT|DELETE/i,k=function(a,b,c,d,f,e,g){g=g||"json";var h="";if(typeof a=="string"){var i=a.indexOf(" ");if(i>2&&i<7){h=a.substr(0,i);if(A.test(h))e=h;else g=h;h=a.substr(i+1)}else h=a}typeof b=="object"&&!s(b)&&(b=t({},b));a=$.String.sub(h,b,true);return $.ajax({url:a,data:b,success:c,error:d,type:e||"post",dataType:g,fixture:f})},l=function(a,b){var c=n(this.shortName),d="-"+c+(a||
"");return $.fixture&&$.fixture[d]?d:b||"//"+n(this.fullName).replace(/\.models\..*/,"").replace(/\./g,"/")+"/fixtures/"+c+(a||"")+".json"},B=function(a,b){a=a||{};var c=this.id;if(a[c]&&a[c]!==b){a["new"+$.String.capitalize(b)]=a[c];delete a[c]}a[c]=b;return a},v=function(a){return new (a||$.Model.List||Array)},o=function(a){return a[a.constructor.id]},C=function(a){for(var b=[],c=0;c<a.length;c++)if(!a[c]["__u Nique"]){b.push(a[c]);a[c]["__u Nique"]=true}for(c=0;c<b.length;c++)delete b[c]["__u Nique"];
return b},w=function(a,b,c,d,f){var e=$.Deferred(),g=[a.serialize(),function(i){a[f||b+"d"](i);e.resolveWith(a,[a,i,b])},function(i){e.rejectWith(a,[i])}],h=a.constructor;b=="destroy"&&g.shift();b!=="create"&&g.unshift(o(a));e.then(c);e.fail(d);h[b].apply(h,g);return e.promise()},p=function(a){return typeof a==="object"&&a!==null&&a},m=function(a){return function(){$.fn[a].apply($([this]),arguments);return this}},x=m("bind");m=m("unbind");ajaxMethods={create:function(a){return function(b,c,d){return k(a,
b,c,d,l.call(this,"Create","-restCreate"))}},update:function(a){return function(b,c,d,f){return k(a,B.call(this,c,b),d,f,l.call(this,"Update","-restUpdate"),"put")}},destroy:function(a){return function(b,c,d){var f={};f[this.id]=b;return k(a,f,c,d,l.call(this,"Destroy","-restDestroy"),"delete")}},findAll:function(a){return function(b,c,d){return k(a||this.shortName+"s.json",b,c,d,l.call(this,"s"),"get","json "+this._shortName+".models")}},findOne:function(a){return function(b,c,d){return k(a,b,c,
d,l.call(this),"get","json "+this._shortName+".model")}}};jQuery.Class("jQuery.Model",{setup:function(a){var b=this;j(["attributes","associations","validations"],function(f,e){if(!b[e]||a[e]===b[e])b[e]={}});j(["convert","serialize"],function(f,e){if(a[e]!=b[e])b[e]=t({},a[e],b[e])});this._fullName=n(this.fullName.replace(/\./g,"_"));this._shortName=n(this.shortName);if(this.fullName.substr(0,7)!="jQuery."){if(this.listType)this.list=new this.listType([]);for(var c in ajaxMethods)if(typeof this[c]!==
"function")this[c]=ajaxMethods[c](this[c]);c={};var d="* "+this._shortName+".model";c[d+"s"]=this.proxy("models");c[d]=this.proxy("model");$.ajaxSetup({converters:c})}},attributes:{},model:function(a){if(!a)return null;if(a instanceof this)a=a.serialize();return new this(p(a[this._shortName])||p(a.data)||p(a.attributes)||a)},models:function(a){if(!a)return null;var b=v(this.List),c=s(a),d=$.Model.List&&a instanceof $.Model.List;d=c?a:d?a.serialize():a.data;var f=d.length,e=0;for(b._use_call=true;e<
f;e++)b.push(this.model(d[e]));if(!c)for(var g in a)if(g!=="data")b[g]=a[g];return b},id:"id",addAttr:function(a,b){if(!this.associations[a]){this.attributes[a]||(this.attributes[a]=b);return b}},_models:{},publish:function(a,b){window.OpenAjax&&OpenAjax.hub.publish(this._shortName+"."+a,b)},guessType:function(){return"string"},convert:{date:function(a){var b=typeof a;return b==="string"?isNaN(Date.parse(a))?null:Date.parse(a):b==="number"?new Date(a):a},number:function(a){return parseFloat(a)},"boolean":function(a){return Boolean(a)},
"default":function(a,b,c){b=$.String.getObject(c);var d=window;if(c.indexOf(".")>=0){c=c.substring(0,c.lastIndexOf("."));d=$.String.getObject(c)}return typeof b=="function"?b.call(d,a):a}},serialize:{"default":function(a){return p(a)&&a.serialize?a.serialize():a}},bind:x,unbind:m,_ajax:k},{setup:function(a){this._init=true;this.attrs(t({},this.constructor.defaults,a));delete this._init},update:function(a,b,c){this.attrs(a);return this.save(b,c)},errors:function(a){if(a)a=s(a)?a:u(arguments);var b=
{},c=this,d=function(g,h){j(h,function(i,q){if(i=q.call(c)){b.hasOwnProperty(g)||(b[g]=[]);b[g].push(i)}})},f=this.constructor.validations;j(a||f||{},function(g,h){if(typeof g=="number"){g=h;h=f[g]}d(g,h||[])});for(var e in b)if(b.hasOwnProperty(e))return b;return null},attr:function(a,b,c,d){var f=z(a),e="get"+f;if(b!==undefined){this._setProperty(a,b,c,d,f);return this}return this[e]?this[e]():this[a]},bind:x,unbind:m,_setProperty:function(a,b,c,d,f){f="set"+f;var e=this[a],g=this,h=function(i){d&&
d.call(g,i);$(g).triggerHandler("error."+a,i)};this[f]&&(b=this[f](b,this.proxy("_updateProperty",a,b,e,c,h),h))===undefined||this._updateProperty(a,b,e,c,h)},_updateProperty:function(a,b,c,d,f){var e=this.constructor,g=e.attributes[a]||e.addAttr(a,e.guessType(b)),h=e.convert[g]||e.convert["default"],i=null,q="",y="updated.";d=d;var r=e.list;b=this[a]=b===null?null:h.call(e,b,function(){},g);this._init||(i=this.errors(a));g=[b];h=[a,b,c];if(i){q=y="error.";d=f;h.splice(1,0,i);g.unshift(i)}if(c!==
b&&!this._init){!i&&$(this).triggerHandler(q+a,g);$(this).triggerHandler(y+"attr",h)}d&&d.apply(this,g);if(a===e.id&&b!==null&&r)if(c){if(c!=b){r.remove(c);r.push(this)}}else r.push(this)},removeAttr:function(a){var b=this[a],c=false,d=this.constructor.attributes;this[a]&&delete this[a];if(d[a]){delete d[a];c=true}!this._init&&c&&b&&$(this).triggerHandler("updated.attr",[a,null,b])},attrs:function(a){var b,c=this.constructor,d=c.attributes;if(a){c=c.id;for(b in a)b!=c&&this.attr(b,a[b]);c in a&&this.attr(c,
a[c])}else{a={};for(b in d)if(d.hasOwnProperty(b))a[b]=this.attr(b)}return a},serialize:function(){var a=this.constructor,b=a.attributes,c,d,f={},e;attributes={};for(e in b)if(b.hasOwnProperty(e)){c=b[e];d=a.serialize[c]||a.serialize["default"];f[e]=d(this[e],c)}return f},isNew:function(){var a=o(this);return a===undefined||a===null},save:function(a,b){return w(this,this.isNew()?"create":"update",a,b)},destroy:function(a,b){return w(this,"destroy",a,b,"destroyed")},identity:function(){var a=o(this),
b=this.constructor;return(b._fullName+"_"+(b.escapeIdentity?encodeURIComponent(a):a)).replace(/ /g,"_")},elements:function(a){return $("."+this.identity(),a)},publish:function(a,b){this.constructor.publish(a,b||this)},hookup:function(a){var b=this.constructor._shortName,c=$.data(a,"models")||$.data(a,"models",{});$(a).addClass(b+" "+this.identity());c[b]=this}});j(["created","updated","destroyed"],function(a,b){$.Model.prototype[b]=function(c){var d=this.constructor;b==="destroyed"&&d.list&&d.list.remove(o(this));
c&&typeof c=="object"&&this.attrs(c.attrs?c.attrs():c);$(this).triggerHandler(b);this.publish(b,this);$([d]).triggerHandler(b,this);return[this].concat(u(arguments))}});$.fn.models=function(){var a=[],b,c;this.each(function(){j($.data(this,"models")||{},function(d,f){b=b===undefined?f.constructor.List||null:f.constructor.List===b?b:null;a.push(f)})});c=v(b);c.push.apply(c,C(a));return c};$.fn.model=function(a){if(a&&a instanceof $.Model){a.hookup(this[0]);return this}else return this.models.apply(this,
arguments)[0]}})(jQuery);
(function(e){var g=e.isArray,j=function(a){var b=0;for(var c in a)b++;return b},f=function(a,b,c){var d=typeof a,h=g(a);if(c===-1)return d==="object"||a===b;if(d!==typeof b||h!==g(b))return false;if(a===b)return true;if(h){if(a.length!==b.length)return false;for(c=0;c<a.length;c++)if(!f(a[c],b[c]))return false;return true}else if(d==="object"||d==="function"){d=0;for(var i in a){if(!f(a[i],b[i],c===false?-1:undefined))return false;d++}return d===j(b)}return false},k=function(a){var b={};for(var c in a)if(typeof a[c]!==
"object"||a[c]===null)b[c]=a[c];return b};e.extend(e.Model.prototype,{backup:function(){this._backupStore=this.serialize();return this},isDirty:function(a){return this._backupStore?!f(this.serialize(),this._backupStore,!!a):false},restore:function(a){this.attrs(a?this._backupStore:k(this._backupStore));return this}})})(jQuery);
(function(d){var l=function(a){return a[0]&&d.isArray(a[0])?a[0]:a[0]instanceof d.Model.List?d.makeArray(a[0]):d.makeArray(a)},q=0,m=function(a){return a[a.constructor.id]},j=jQuery.expando,k=d.each,n=d.Model._ajax,o={update:function(a){return function(b,c,e,g){return n(a,{ids:b,attrs:c},e,g,"-updateAll","put")}},destroy:function(a){return function(b,c,e){return n(a,b,c,e,"-destroyAll","post")}}};d.Class("jQuery.Model.List",{setup:function(){for(var a in o)if(typeof this[a]!=="function")this[a]=o[a](this[a])}},
{init:function(a){this.length=0;this._data={};this._namespace=".list"+ ++q;this.push.apply(this,d.makeArray(a||[]))},slice:function(){return new this.Class(Array.prototype.slice.apply(this,arguments))},match:function(a,b){return this.grep(function(c){return c[a]==b})},grep:function(a,b){return new this.Class(d.grep(this,a,b))},_makeData:function(){var a=this._data={};this.each(function(b,c){a[c[c.constructor.id]]=c})},get:function(){if(!this.length)return new this.Class([]);this._changed&&this._makeData();
var a=[],b=this[0].constructor,c=b.id;b=new RegExp(b._fullName+"_([^ ]+)");for(var e,g,f=l(arguments),h=0;h<f.length;h++)(g=f[h].nodeName&&(e=f[h].className.match(b))?this._data[e[1]]:this._data[typeof f[h]=="string"||typeof f[h]=="number"?f[h]:f[h][c]])&&a.push(g);return new this.Class(a)},remove:function(a){if(!this.length)return[];var b=[],c=this[0].constructor,e=c.id;c=new RegExp(c._fullName+"_([^ ]+)");var g;a=l(arguments);for(var f=0;f<this.length;){for(var h=this[f],p=false,i=0;i<a.length;i++){var r=
a[i].nodeName&&(g=a[i].className.match(c))&&g[1]||(typeof a[i]=="string"||typeof a[i]=="number"?a[i]:a[i][e]);if(h[e]==r){b.push.apply(b,this.splice(f,1));a.splice(i,1);p=true;break}}p||f++}b=new this.Class(b);b.length&&d([this]).trigger("remove",[b]);return b},elements:function(a){return d(this.map(function(b){return"."+b.identity()}).join(","),a)},model:function(){return this.constructor.namespace},findAll:function(a,b,c){var e=this;this.model().findAll(a,function(g){e.push(g);b&&b(e)},c)},destroy:function(a,
b){var c=this.map(m),e=this.slice(0,this.length);if(c.length)this.constructor.destroy(c,function(){k(e,function(){this.destroyed()});a&&a(e)},b);else a&&a(this);return this},update:function(a,b,c){var e=this.map(m),g=this.slice(0,this.length);if(e.length)this.constructor.update(e,a,function(f){var h=d.extend(a,f||{});k(g,function(){this.updated(h)});b&&b(g)},c);else b&&b(this);return this},bind:function(){this[j]===undefined&&this.bindings(this);d.fn.bind.apply(d([this]),arguments);return this},unbind:function(){d.fn.unbind.apply(d([this]),
arguments);this[j]===undefined&&d(this).unbind(this._namespace);return this},bindings:function(a){var b=this;d(a).bind("destroyed"+this._namespace,function(){b.remove(this)}).bind("updated"+this._namespace,function(){d([b]).trigger("updated",this)})},push:function(){var a=l(arguments);this[j]!==undefined&&this.bindings(a);this._changed=true;var b=s.apply(this,a);this[j]&&a.length&&d([this]).trigger("add",[a]);return b},serialize:function(){return this.map(function(a){return a.serialize()})}});var s=
[].push;k({pop:[].pop,shift:[].shift,unshift:[].unshift,splice:[].splice,sort:[].sort},function(a,b){d.Model.List.prototype[a]=function(){this._changed=true;return b.apply(this,arguments)}});k(["each","map"],function(a,b){d.Model.List.prototype[b]=function(c,e){return d[b](this,c,e)}})})(jQuery);
(function(g){var f=function(d,a,b){if(!b){b=a;a={}}a=a||{};d=g.makeArray(d);if(!(a.testIf&&!a.testIf.call(this))){var c=this;g.each(d,function(e,h){c.validations[h]||(c.validations[h]=[]);c.validations[h].push(function(){var i=b.call(this,this[h]);return i===undefined?undefined:a.message||i})})}};g.extend(g.Model,{validate:f,validationMessages:{format:"is invalid",inclusion:"is not a valid option (perhaps out of range)",lengthShort:"is too short",lengthLong:"is too long",presence:"can't be empty",
range:"is out of range"},validateFormatOf:function(d,a,b){f.call(this,d,b,function(c){if(typeof c!="undefined"&&c!=""&&String(c).match(a)==null)return this.Class.validationMessages.format})},validateInclusionOf:function(d,a,b){f.call(this,d,b,function(c){if(typeof c!="undefined")if(g.grep(a,function(e){return e==c}).length==0)return this.Class.validationMessages.inclusion})},validateLengthOf:function(d,a,b,c){f.call(this,d,c,function(e){if(typeof e=="undefined"&&a>0||e.length<a)return this.Class.validationMessages.lengthShort+
" (min="+a+")";else if(typeof e!="undefined"&&e.length>b)return this.Class.validationMessages.lengthLong+" (max="+b+")"})},validatePresenceOf:function(d,a){f.call(this,d,a,function(b){if(typeof b=="undefined"||b==""||b===null)return this.Class.validationMessages.presence})},validateRangeOf:function(d,a,b,c){f.call(this,d,c,function(e){if(typeof e!="undefined"&&e<a||e>b)return this.Class.validationMessages.range+" ["+a+","+b+"]"})}})})(jQuery);
(function(a){function h(d){d=d||window[e][i];return d.replace(/^[^#]*#?(.*)$/,"$1")}var k,o=a.event.special,e="location",i="href",p=document.documentMode,q=a.browser.msie&&(p===undefined||p<8),r="onhashchange"in window&&!q;a.hashchangeDelay=100;o.hashchange=a.extend(o.hashchange,{setup:function(){if(r)return false;a(k.start)},teardown:function(){if(r)return false;a(k.stop)}});k=function(){function d(){f=l=function(b){return b};if(q){j=a('<iframe src="javascript:0"/>').hide().insertAfter("body")[0].contentWindow;
l=function(){return h(j.document[e][i])};f=function(b,c){if(b!==c){c=j.document;c.open().close();c[e].hash="#"+b}};f(h())}}var m={},g,j,f,l;m.start=function(){if(!g){var b=h();f||d();navigator.userAgent.match(/Rhino/)||function c(){var s=h(),n=l(b);if(s!==b){f(b=s,n);a(window).trigger("hashchange")}else if(n!==b)window[e][i]=window[e][i].replace(/#.*/,"")+"#"+n;g=setTimeout(c,a.hashchangeDelay)}()}};m.stop=function(){if(!j){g&&clearTimeout(g);g=0}};return m}()})(jQuery);
(function(){var j=$.event,k=function(a){return(typeof HTMLElement==="object"?a instanceof HTMLElement:typeof a==="object"&&a.nodeType===1&&typeof a.nodeName==="string")||a===window||a===document};$.event.trigger=function(a,g,d,e){var b=a.type||a,c=[],h;if(b.indexOf("!")>=0){b=b.slice(0,-1);h=true}if(b.indexOf(".")>=0){c=b.split(".");b=c.shift();c.sort()}if(!((!d||jQuery.event.customEvent[b])&&!jQuery.event.global[b])){a=typeof a==="object"?a[jQuery.expando]?a:new jQuery.Event(b,a):new jQuery.Event(b);
a.type=b;a.exclusive=h;a.namespace=c.join(".");a.namespace_re=new RegExp("(^|\\.)"+c.join("\\.(?:.*\\.)?")+"(\\.|$)");if(e||!d){a.preventDefault();a.stopPropagation()}if(d){if(!(d.nodeType===3||d.nodeType===8)){a.result=undefined;a.target=d;g=g?jQuery.makeArray(g):[];g.unshift(a);c=d;e=b.indexOf(":")<0?"on"+b:"";do{h=jQuery._data(c,"handle");a.currentTarget=c;h&&h.apply(c,g);if(e&&jQuery.acceptData(c)&&c[e]&&c[e].apply(c,g)===false){a.result=false;a.preventDefault()}c=c.parentNode||c.ownerDocument||
c===a.target.ownerDocument&&window}while(c&&!a.isPropagationStopped());if(!a.isDefaultPrevented()){var f;c=jQuery.event.special[b]||{};if((!c._default||c._default.call(d.ownerDocument,a)===false)&&!(b==="click"&&jQuery.nodeName(d,"a"))&&jQuery.acceptData(d)){try{if(e&&d[b]){if(f=d[e])d[e]=null;jQuery.event.triggered=b;d[b]()}}catch(l){}if(f)d[e]=f;jQuery.event.triggered=undefined}}return a.result}}else jQuery.each(jQuery.cache,function(){var i=this[jQuery.expando];i&&i.events&&i.events[b]&&jQuery.event.trigger(a,
g,i.handle.elem)})}};$.event.handle=function(a){a=jQuery.event.fix(a||window.event);var g=((jQuery._data(this,"events")||{})[a.type]||[]).slice(0),d=!a.exclusive&&!a.namespace,e=Array.prototype.slice.call(arguments,0);e[0]=a;a.currentTarget=this;var b=a.type,c=a.type!=="default"&&j.special["default"]&&!a.originalEvent&&k(a.target);c&&j.special["default"].triggerDefault(a,this,e[1]);a.type=b;b=0;for(var h=g.length;b<h;b++){var f=g[b];if(a.firstPass)a.firstPass=false;else if(d||a.namespace_re.test(f.namespace)){a.handler=
f.handler;a.data=f.data;a.handleObj=f;f=f.handler.apply(this,e);if(f!==undefined){a.result=f;if(f===false){a.preventDefault();a.stopPropagation()}}if(a.isImmediatePropagationStopped())break}}c&&j.special["default"].checkAndRunDefaults(a,this);return a.result}})(jQuery);
(function(g){g.fn.triggerAsync=function(a,b,d,c){if(typeof b=="function"){d=b;b=undefined}if(this[0]){var e=g.Event(a),f=e.preventDefault;e.preventDefault=function(){f.apply(this,arguments);c&&c(this)};jQuery.event.trigger({type:a,_success:d},b,this[0])}else d.call(this);return this};var j={},k=/\.(.*)$/,h=g.event;h.special["default"]={add:function(a){j[a.namespace.replace(k,"")]=true;var b=a.handler;a.origHandler=b;a.handler=function(d,c){if(!d._defaultActions)d._defaultActions=[];d._defaultActions.push({element:this,
handler:b,event:d,data:c,currentTarget:d.currentTarget})}},setup:function(){return true},triggerDefault:function(a,b,d){var c=jQuery.Event("default."+a.type);g.extend(c,{target:b,_defaultActions:a._defaultActions,exclusive:true});c.stopPropagation();if(b){a=c.type||a;var e=[],f;if(a.indexOf("!")>=0){a=a.slice(0,-1);f=true}if(a.indexOf(".")>=0){e=a.split(".");a=e.shift();e.sort()}c.type=a;c.exclusive=f;h.handle.call(b,c,d)}},checkAndRunDefaults:function(a,b){if(!a.isDefaultPrevented()&&(!a.isPaused||
!a.isPaused())&&a._defaultActions&&(a.isPropagationStopped()||!b.parentNode&&!b.ownerDocument)){b=a.namespace;var d=a.type,c=a.liveFired;a.namespace=a.type;a.type="default";a.liveFired=null;for(var e=0;e<a._defaultActions.length;e++){var f=a._defaultActions[e],l=a.handled;a.currentTarget=f.currentTarget;f.handler.call(f.element,a,f.data);a.handled=a.handled===null?l:true}a._defaultActions=null;a._success&&a._success(a);a.namespace=b;a.type=d;a.liveFired=c}}};var m=h.trigger,i=jQuery._data;g._data=
function(a,b,d){if(!d&&b==="handle"){i.apply(this,arguments);return function(c){return typeof jQuery!=="undefined"&&(!c||jQuery.event.triggered!==c.type)?jQuery.event.handle.apply(this,arguments):undefined}}return i.apply(this,arguments)};h.trigger=function(a,b,d,c){var e=a.type||a;a=typeof a==="object"?a[jQuery.expando]?a:new jQuery.Event(e,a):new jQuery.Event(e);a._defaultActions=[];m.call(g.event,a,b,d,c)}})(jQuery);
(function(c){var f=function(a){return a!==undefined?(this.array[0]=a):this.array[0]},g=function(a){return a!==undefined?(this.array[1]=a):this.array[1]};c.Vector=function(){this.update(c.makeArray(arguments))};c.Vector.prototype={app:function(a){var b,d=[];for(b=0;b<this.array.length;b++)d.push(a(this.array[b]));return(new c.Vector).update(d)},plus:function(){var a,b=arguments[0]instanceof c.Vector?arguments[0].array:c.makeArray(arguments),d=this.array.slice(0),e=new c.Vector;for(a=0;a<b.length;a++)d[a]=
(d[a]?d[a]:0)+b[a];return e.update(d)},minus:function(){var a,b=arguments[0]instanceof c.Vector?arguments[0].array:c.makeArray(arguments),d=this.array.slice(0),e=new c.Vector;for(a=0;a<b.length;a++)d[a]=(d[a]?d[a]:0)-b[a];return e.update(d)},equals:function(){var a,b=arguments[0]instanceof c.Vector?arguments[0].array:c.makeArray(arguments),d=this.array.slice(0),e=new c.Vector;for(a=0;a<b.length;a++)if(d[a]!=b[a])return null;return e.update(d)},x:f,width:f,y:g,height:g,top:g,left:f,toString:function(){return"("+
this.array[0]+","+this.array[1]+")"},update:function(a){var b;if(this.array)for(b=0;b<this.array.length;b++)delete this.array[b];this.array=a;for(b=0;b<a.length;b++)this[b]=this.array[b];return this}};c.Event.prototype.vector=function(){if(this.originalEvent.synthetic){var a=document.documentElement,b=document.body;return new c.Vector(this.clientX+(a&&a.scrollLeft||b&&b.scrollLeft||0)-(a.clientLeft||0),this.clientY+(a&&a.scrollTop||b&&b.scrollTop||0)-(a.clientTop||0))}else return new c.Vector(this.pageX,
this.pageY)};c.fn.offsetv=function(){if(this[0]==window)return new c.Vector(window.pageXOffset?window.pageXOffset:document.documentElement.scrollLeft,window.pageYOffset?window.pageYOffset:document.documentElement.scrollTop);else{var a=this.offset();return new c.Vector(a.left,a.top)}};c.fn.dimensionsv=function(a){return this[0]==window||!a?new c.Vector(this.width(),this.height()):new c.Vector(this[a+"Width"](),this[a+"Height"]())}})(jQuery);
(function(){var h=jQuery.event,l=function(a,e,f){var g,c,b,d,i,j,k;for(g=0;g<e.length;g++){c=e[g];d=c.indexOf(".")<0;if(!d){b=c.split(".");c=b.shift();k=new RegExp("(^|\\.)"+b.slice(0).sort().join("\\.(?:.*\\.)?")+"(\\.|$)")}b=(a[c]||[]).slice(0);for(i=0;i<b.length;i++){j=b[i];if(!j.selector&&(d||k.test(j.namespace)))f(c,j.origHandler||j.handler)}}};h.find=function(a,e,f){a=$.data(a,"events");var g=[],c,b;if(!a)return g;if(f){if(!a.live)return[];b=a.live;for(a=0;a<b.length;a++){c=b[a];if(c.selector===
f&&$.inArray(c.origType,e)!==-1)g.push(c.origHandler||c.handler)}}else l(a,e,function(d,i){g.push(i)});return g};h.findBySelector=function(a,e){a=$.data(a,"events");var f={},g=function(c,b,d){c=f[c]||(f[c]={});(c[b]||(c[b]=[])).push(d)};if(!a)return f;$.each(a.live||[],function(c,b){if($.inArray(b.origType,e)!==-1)g(b.selector,b.origType,b.origHandler||b.handler)});l(a,e,function(c,b){g("",c,b)});return f};h.supportTouch="ontouchend"in document;$.fn.respondsTo=function(a){return this.length?h.find(this[0],
$.isArray(a)?a:[a]).length>0:false};$.fn.triggerHandled=function(a,e){a=typeof a=="string"?$.Event(a):a;this.trigger(a,e);return a.handled};h.setupHelper=function(a,e,f){if(!f){f=e;e=null}var g=function(b){var d=b.selector||"";if(d){b=h.find(this,a,d);b.length||$(this).delegate(d,e,f)}else h.find(this,a,d).length||h.add(this,e,f,{selector:d,delegate:this})},c=function(b){var d=b.selector||"";if(d){b=h.find(this,a,d);b.length||$(this).undelegate(d,e,f)}else h.find(this,a,d).length||h.remove(this,e,
f,{selector:d,delegate:this})};$.each(a,function(){h.special[this]={add:g,remove:c,setup:function(){},teardown:function(){}}})}})(jQuery);
(function(c){var h=function(a,b){var d=Array.prototype.slice.call(arguments,2);return function(){var e=[this].concat(d,c.makeArray(arguments));return b.apply(a,e)}},g=c.event,i=window.getSelection?function(){window.getSelection().removeAllRanges()}:function(){};c.Drag=function(){};c.extend(c.Drag,{lowerName:"drag",current:null,distance:0,mousedown:function(a,b){if(!(!(a.button===0||a.button==1)||this.current)){var d=new c.Drag,e=a.liveFired||b,f=a.handleObj.selector,j=this;this.current=d;d.setup({element:b,
delegate:a.liveFired||b,selector:a.handleObj.selector,moved:false,_distance:this.distance,callbacks:{dragdown:g.find(e,["dragdown"],f),draginit:g.find(e,["draginit"],f),dragover:g.find(e,["dragover"],f),dragmove:g.find(e,["dragmove"],f),dragout:g.find(e,["dragout"],f),dragend:g.find(e,["dragend"],f)},destroyed:function(){j.current=null}},a)}}});c.extend(c.Drag.prototype,{setup:function(a,b){c.extend(this,a);this.element=c(this.element);this.event=b;this.allowOtherDrags=this.moved=false;var d=h(this,
this.mousemove),e=h(this,this.mouseup);this._mousemove=d;this._mouseup=e;this._distance=a.distance?a.distance:0;this.mouseStartPosition=b.vector();c(document).bind("mousemove",d);c(document).bind("mouseup",e);if(!this.callEvents("down",this.element,b)){this.noSelection(this.delegate);i()}},destroy:function(){c(document).unbind("mousemove",this._mousemove);c(document).unbind("mouseup",this._mouseup);if(!this.moved)this.event=this.element=null;this.selection(this.delegate);this.destroyed()},mousemove:function(a,
b){if(!this.moved){if(Math.sqrt(Math.pow(b.pageX-this.event.pageX,2)+Math.pow(b.pageY-this.event.pageY,2))<this._distance)return false;this.init(this.element,b);this.moved=true}a=b.vector();this._start_position&&this._start_position.equals(a)||this.draw(a,b)},mouseup:function(a,b){this.moved&&this.end(b);this.destroy()},noSelection:function(a){a=a||this.delegate;document.documentElement.onselectstart=function(){return false};document.documentElement.unselectable="on";this.selectionDisabled=this.selectionDisabled?
this.selectionDisabled.add(a):c(a);this.selectionDisabled.css("-moz-user-select","-moz-none")},selection:function(){if(this.selectionDisabled){document.documentElement.onselectstart=function(){};document.documentElement.unselectable="off";this.selectionDisabled.css("-moz-user-select","")}},init:function(a,b){a=c(a);var d=this.movingElement=this.element=c(a);this._cancelled=false;this.event=b;this.mouseElementPosition=this.mouseStartPosition.minus(this.element.offsetv());this.callEvents("init",a,b);
if(this._cancelled!==true){this.startPosition=d!=this.movingElement?this.movingElement.offsetv():this.currentDelta();this.makePositioned(this.movingElement);this.oldZIndex=this.movingElement.css("zIndex");this.movingElement.css("zIndex",1E3);!this._only&&this.constructor.responder&&this.constructor.responder.compile(b,this)}},makePositioned:function(a){var b;b=a.css("position");if(!b||b=="static"){b={position:"relative"};if(window.opera){b.top="0px";b.left="0px"}a.css(b)}},callEvents:function(a,b,
d,e){var f=this.callbacks[this.constructor.lowerName+a];for(a=0;a<f.length;a++)f[a].call(b,d,this,e);return f.length},currentDelta:function(){return new c.Vector(parseInt(this.movingElement.css("left"),10)||0,parseInt(this.movingElement.css("top"),10)||0)},draw:function(a,b){if(!this._cancelled){i();this.location=a.minus(this.mouseElementPosition);this.move(b);if(!this._cancelled){b.isDefaultPrevented()||this.position(this.location);!this._only&&this.constructor.responder&&this.constructor.responder.show(a,
this,b)}}},position:function(a){var b=this.currentDelta();b=this.movingElement.offsetv().minus(b);this.required_css_position=a.minus(b);this.offsetv=a;a=this.movingElement[0].style;if(!this._cancelled&&!this._horizontal)a.top=this.required_css_position.top()+"px";if(!this._cancelled&&!this._vertical)a.left=this.required_css_position.left()+"px"},move:function(a){this.callEvents("move",this.element,a)},over:function(a,b){this.callEvents("over",this.element,a,b)},out:function(a,b){this.callEvents("out",
this.element,a,b)},end:function(a){if(!this._cancelled){!this._only&&this.constructor.responder&&this.constructor.responder.end(a,this);this.callEvents("end",this.element,a);if(this._revert){var b=this;this.movingElement.animate({top:this.startPosition.top()+"px",left:this.startPosition.left()+"px"},function(){b.cleanup.apply(b,arguments)})}else this.cleanup();this.event=null}},cleanup:function(){this.movingElement.css({zIndex:this.oldZIndex});this.movingElement[0]!==this.element[0]&&!this.movingElement.has(this.element[0]).length&&
!this.element.has(this.movingElement[0]).length&&this.movingElement.css({display:"none"});this._removeMovingElement&&this.movingElement.remove();this.movingElement=this.element=this.event=null},cancel:function(){this._cancelled=true;!this._only&&this.constructor.responder&&this.constructor.responder.clear(this.event.vector(),this,this.event);this.destroy()},ghost:function(a){var b=this.movingElement.clone().css("position","absolute");(a?c(a):this.movingElement).after(b);b.width(this.movingElement.width()).height(this.movingElement.height());
b.offset(this.movingElement.offset());this.movingElement=b;this.noSelection(b);this._removeMovingElement=true;return b},representative:function(a,b,d){this._offsetX=b||0;this._offsetY=d||0;b=this.mouseStartPosition;this.movingElement=c(a);this.movingElement.css({top:b.y()-this._offsetY+"px",left:b.x()-this._offsetX+"px",display:"block",position:"absolute"}).show();this.noSelection(this.movingElement);this.mouseElementPosition=new c.Vector(this._offsetX,this._offsetY)},revert:function(a){this._revert=
a===undefined?true:a;return this},vertical:function(){this._vertical=true;return this},horizontal:function(){return this._horizontal=true},only:function(a){return this._only=a===undefined?true:a},distance:function(a){if(a!==undefined){this._distance=a;return this}else return this._distance}});g.setupHelper(["dragdown","draginit","dragover","dragmove","dragout","dragend"],"mousedown",function(a){c.Drag.mousedown.call(c.Drag,a,this)})})(jQuery);

(function(f){var i=document.defaultView&&document.defaultView.getComputedStyle,o=/([A-Z])/g,l=/-([a-z])/ig,m=function(a,g){return g.toUpperCase()},p=function(a){if(i)return i(a,null);else if(a.currentStyle)return a.currentStyle},q=/float/i,r=/^-?\d+(?:px)?$/i,s=/^-?\d/;f.curStyles=function(a,g){if(!a)return null;for(var j=p(a),c,d,h=a.style,e={},k=0,b,n;k<g.length;k++){b=g[k];c=b.replace(l,m);if(q.test(b)){b=jQuery.support.cssFloat?"float":"styleFloat";c="cssFloat"}if(i){b=b.replace(o,"-$1").toLowerCase();
d=j.getPropertyValue(b);if(b==="opacity"&&d==="")d="1";e[c]=d}else{d=b.replace(l,m);e[c]=j[b]||j[d];if(!r.test(e[c])&&s.test(e[c])){b=h.left;n=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;h.left=d==="fontSize"?"1em":e[c]||0;e[c]=h.pixelLeft+"px";h.left=b;a.runtimeStyle.left=n}}}return e};f.fn.curStyles=function(){return f.curStyles(this[0],f.makeArray(arguments))}})(jQuery);
(function(e){e.Drag.prototype.limit=function(b,c){var a=b.curStyles("borderTopWidth","paddingTop","borderLeftWidth","paddingLeft");a=new e.Vector(parseInt(a.borderLeftWidth,10)+parseInt(a.paddingLeft,10)||0,parseInt(a.borderTopWidth,10)+parseInt(a.paddingTop,10)||0);this._limit={offset:b.offsetv().plus(a),size:b.dimensionsv(),center:c===true?"both":c};return this};var j=e.Drag.prototype.position;e.Drag.prototype.position=function(b){if(this._limit){var c=this._limit,a=c.center&&c.center.toLowerCase(),
d=this.movingElement.dimensionsv("outer"),f=a&&a!="x"?d.height()/2:0;a=a&&a!="y"?d.width()/2:0;var g=c.offset.top(),h=c.offset.left(),i=c.size.height();c=c.size.width();b.top()+f<g&&b.top(g-f);b.top()+d.height()-f>g+i&&b.top(g+i-d.height()+f);b.left()+a<h&&b.left(h-a);b.left()+d.width()-a>h+c&&b.left(h+c-d.left()+a)}j.call(this,b)}})(jQuery);
(function(i){var j=function(b,c,e,d,a,g){return c>=d&&c<d+g&&b>=e&&b<e+a};i.fn.within=function(b,c,e){var d=[];this.each(function(){var a=jQuery(this);if(this==document.documentElement)return d.push(this);a=e?jQuery.data(this,"offsetCache")||jQuery.data(this,"offsetCache",a.offset()):a.offset();j(b,c,a.left,a.top,this.offsetWidth,this.offsetHeight)&&d.push(this)});return this.pushStack(jQuery.unique(d),"within",b+","+c)};i.fn.withinBox=function(b,c,e,d,a){var g=[];this.each(function(){var f=jQuery(this);
if(this==document.documentElement)return this.ret.push(this);var h=a?jQuery.data(this,"offset",f.offset()):f.offset(),k=f.width();f=f.height();(res=!(h.top>c+d||h.top+f<c||h.left>b+e||h.left+k<b))&&g.push(this)});return this.pushStack(jQuery.unique(g),"withinBox",jQuery.makeArray(arguments).join(","))}})(jQuery);
(function(){jQuery.fn.compare=function(a){try{a=a.jquery?a[0]:a}catch(e){return null}if(window.HTMLElement){var b=HTMLElement.prototype.toString.call(a);if(b=="[xpconnect wrapped native prototype]"||b=="[object XULElement]"||b==="[object Window]")return null}if(this[0].compareDocumentPosition)return this[0].compareDocumentPosition(a);if(this[0]==document&&a!=document)return 8;b=(this[0]!==a&&this[0].contains(a)&&16)+(this[0]!=a&&a.contains(this[0])&&8);var c=document.documentElement;if(this[0].sourceIndex){b+=
this[0].sourceIndex<a.sourceIndex&&4;b+=this[0].sourceIndex>a.sourceIndex&&2;b+=(this[0].ownerDocument!==a.ownerDocument||this[0]!=c&&this[0].sourceIndex<=0||a!=c&&a.sourceIndex<=0)&&1}else{c=document.createRange();var d=document.createRange();c.selectNode(this[0]);d.selectNode(a);c.compareBoundaryPoints(Range.START_TO_START,d)}return b}})(jQuery);
(function(f){var m=f.event,k=["dropover","dropon","dropout","dropinit","dropmove","dropend"];f.Drop=function(a,b){jQuery.extend(this,a);this.element=f(b)};f.each(k,function(){m.special[this]={add:function(){var a=f(this),b=a.data("dropEventCount")||0;a.data("dropEventCount",b+1);b==0&&f.Drop.addElement(this)},remove:function(){var a=f(this),b=a.data("dropEventCount")||0;a.data("dropEventCount",b-1);b<=1&&f.Drop.removeElement(this)}}});f.extend(f.Drop,{lowerName:"drop",_rootElements:[],_elements:f(),
last_active:[],endName:"dropon",addElement:function(a){for(var b=0;b<this._rootElements.length;b++)if(a==this._rootElements[b])return;this._rootElements.push(a)},removeElement:function(a){for(var b=0;b<this._rootElements.length;b++)if(a==this._rootElements[b]){this._rootElements.splice(b,1);return}},sortByDeepestChild:function(a,b){a=a.element.compare(b.element);if(a&16||a&4)return 1;if(a&8||a&2)return-1;return 0},isAffected:function(a,b,c){return c.element!=b.element&&c.element.within(a[0],a[1],
c._cache).length==1},deactivate:function(a,b,c){b.out(c,a);a.callHandlers(this.lowerName+"out",a.element[0],c,b)},activate:function(a,b,c){b.over(c,a);a.callHandlers(this.lowerName+"over",a.element[0],c,b)},move:function(a,b,c){a.callHandlers(this.lowerName+"move",a.element[0],c,b)},compile:function(a,b){if(this.dragging||b){if(!this.dragging){this.dragging=b;this.last_active=[]}for(var c,d,e,g=[],i=this.dragging,h=0;h<this._rootElements.length;h++){b=this._rootElements[h];c=f.event.findBySelector(b,
k);for(d in c){e=d?jQuery(d,b):[b];for(var j=0;j<e.length;j++)this.addCallbacks(e[j],c[d],i)&&g.push(e[j])}}this.add(g,a,i)}},addCallbacks:function(a,b,c){var d=f.data(a,"_dropData");if(d){if(!c){for(var e in b)d[e]=d[e]?d[e].concat(b[e]):b[e];return false}}else{f.data(a,"_dropData",new f.Drop(b,a));return true}},add:function(a,b,c){for(var d=0,e;d<a.length;){e=f.data(a[d],"_dropData");e.callHandlers(this.lowerName+"init",a[d],b,c);if(e._canceled)a.splice(d,1);else d++}this._elements.push.apply(this._elements,
a)},show:function(a,b,c){if(this._elements.length){var d=[],e=true,g=0,i,h,j,l=this.last_active;for(i=this;g<this._elements.length;)if(h=f.data(this._elements[g],"_dropData")){g++;i.isAffected(a,b,h)&&d.push(h)}else this._elements.splice(g,1);d.sort(this.sortByDeepestChild);c.stopRespondPropagate=function(){e=false};h=d.slice();this.last_active=d;for(a=0;a<l.length;a++){i=l[a];for(g=0;j=h[g];)if(i==j){h.splice(g,1);break}else g++;j||this.deactivate(i,b,c);if(!e)return}for(g=0;g<h.length;g++){this.activate(h[g],
b,c);if(!e)return}for(g=0;g<d.length;g++){this.move(d[g],b,c);if(!e)return}}},end:function(a,b){for(var c,d=this.lowerName+"end",e=0;e<this.last_active.length;e++){c=this.last_active[e];this.isAffected(a.vector(),b,c)&&c[this.endName]&&c.callHandlers(this.endName,null,a,b)}for(c=0;c<this._elements.length;c++)f.data(this._elements[c],"_dropData").callHandlers(d,null,a,b);this.clear()},clear:function(){this._elements.each(function(){f.removeData(this,"_dropData")});this._elements=f();delete this.dragging}});
f.Drag.responder=f.Drop;f.extend(f.Drop.prototype,{callHandlers:function(a,b,c,d){for(var e=this[a]?this[a].length:0,g=0;g<e;g++)this[a][g].call(b||this.element[0],c,this,d)},cache:function(a){this._cache=a!=null?a:true},cancel:function(){this._canceled=true}})})(jQuery);
(function(f){f.Drag.prototype.scrolls=function(a,c){a=f(a);for(var b=0;b<a.length;b++)this.constructor.responder._elements.push(a.eq(b).data("_dropData",new f.Scrollable(a[b],c))[0])};f.Scrollable=function(a,c){this.element=jQuery(a);this.options=f.extend({distance:30,delta:function(b,g){return(g-b)/2},direction:"xy"},c);this.x=this.options.direction.indexOf("x")!=-1;this.y=this.options.direction.indexOf("y")!=-1};f.extend(f.Scrollable.prototype,{init:function(a){this.element=jQuery(a)},callHandlers:function(a,
c,b,g){this[a](c||this.element[0],b,this,g)},dropover:function(){},dropon:function(){this.clear_timeout()},dropout:function(){this.clear_timeout()},dropinit:function(){},dropend:function(){},clear_timeout:function(){if(this.interval){clearTimeout(this.interval);this.interval=null}},distance:function(a){return(30-a)/2},dropmove:function(a,c,b,g){this.clear_timeout();var d=c.vector();b=f(a==document.documentElement?window:a);var h=b.dimensionsv("outer"),e=b.offsetv();b=e.y()+h.y()-d.y();var k=d.y()-
e.y();h=e.x()+h.x()-d.x();d=d.x()-e.x();var i=0,j=0;e=this.options.distance;if(b<e&&this.y)j=this.options.delta(b,e);else if(k<e&&this.y)j=-this.options.delta(k,e);if(h<e&&this.options&&this.x)i=this.options.delta(h,e);else if(d<e&&this.x)i=-this.options.delta(d,e);if(i||j){var l=this;this.interval=setTimeout(function(){l.move(f(a),g.movingElement,i,j,c,c.clientX,c.clientY,c.screenX,c.screenY)},15)}},move:function(a,c,b,g,d){a.scrollTop(a.scrollTop()+g);a.scrollLeft(a.scrollLeft()+b);c.trigger(f.event.fix({type:"mousemove",
clientX:d.clientX,clientY:d.clientY,screenX:d.screenX,screenY:d.screenY,pageX:d.pageX,pageY:d.pageY}))}})})(jQuery);
(function(e){var f=function(a,b){return Math.round(a/b)*b};e.Drag.prototype.step=function(a,b,d){if(typeof a=="number")a={x:a,y:a};b=b||e(document.body);this._step=a;var c=b.curStyles("borderTopWidth","paddingTop","borderLeftWidth","paddingLeft");a=parseInt(c.borderTopWidth)+parseInt(c.paddingTop);c=parseInt(c.borderLeftWidth)+parseInt(c.paddingLeft);this._step.offset=b.offsetv().plus(c,a);this._step.center=d;return this};var h=e.Drag.prototype.position;e.Drag.prototype.position=function(a){if(this._step){var b=
this._step,d=b.center&&b.center.toLowerCase(),c=this.movingElement.dimensionsv("outer"),g=b.offset.top()-(d&&d!="x"?c.height()/2:0);b=b.offset.left()-(d&&d!="y"?c.width()/2:0);this._step.x&&a.left(Math.round(b+f(a.left()-b,this._step.x)));this._step.y&&a.top(Math.round(g+f(a.top()-g,this._step.y)))}h.call(this,a)}})(jQuery);
(function(a){a.Hover=function(){this._delay=a.Hover.delay;this._distance=a.Hover.distance;this._leave=a.Hover.leave};a.extend(a.Hover,{delay:100,distance:10,leave:0});a.extend(a.Hover.prototype,{delay:function(b){this._delay=b;return this},distance:function(b){this._distance=b;return this},leave:function(b){this._leave=b;return this}});var h=a.event;h.setupHelper(["hoverinit","hoverenter","hoverleave","hovermove"],"mouseenter",function(b){var e=b.liveFired||b.currentTarget,f=b.handleObj.selector;
if(!a.data(e,"_hover"+f)){a.data(e,"_hover"+f,true);var i={pageX:b.pageX,pageY:b.pageY},j=0,k,d=this,m=false,n=b,c=new a.Hover,l,p=function(){a.each(h.find(e,["hoverleave"],f),function(){this.call(d,b,c)});o()},q=function(g){clearTimeout(l);j+=Math.pow(g.pageX-i.pageX,2)+Math.pow(g.pageY-i.pageY,2);i={pageX:g.pageX,pageY:g.pageY};n=g},r=function(){clearTimeout(k);if(m)if(c._leave===0)p();else{clearTimeout(l);l=setTimeout(function(){p()},c._leave)}else o()},o=function(){a(d).unbind("mouseleave",r);
a(d).unbind("mousemove",q);a.removeData(e,"_hover"+f)};a(d).bind("mousemove",q).bind("mouseleave",r);a.each(h.find(e,["hoverinit"],f),function(){this.call(d,b,c)});k=setTimeout(function(){if(j<c._distance&&a(d).queue().length==0){a.each(h.find(e,["hoverenter"],f),function(){this.call(d,n,c)});m=true}else{j=0;k=setTimeout(arguments.callee,c._delay)}},c._delay)}})})(jQuery);
(function(b){var c=b(),j=0,d=b(window),k=0,l=0,m;b(function(){k=d.width();l=d.height()});b.event.special.resize={setup:function(){if(this!==window){c.push(this);b.unique(c)}return this!==window},teardown:function(){c=c.not(this);return this!==window},add:function(h){h.origHandler=h.handler;h.handler=function(a,e){var f=this===window;if(f&&a.originalEvent){a=d.width();f=d.height();if(a!=k||f!=l){k=a;l=f;clearTimeout(m);m=setTimeout(function(){d.trigger("resize")},1)}}else if(j===0){j++;e=e===false?
a.target:this;b.event.handle.call(e,a);if(!a.isPropagationStopped()){for(var g=c.index(this),n=c.length,i,o;++g<n&&(i=c[g])&&(f||b.contains(e,i));){b.event.handle.call(i,a);if(a.isPropagationStopped())for(;++g<n&&(o=c[g]);)if(!b.contains(i,o)){g--;break}}a.stopImmediatePropagation()}j--}else h.origHandler.call(this,a,e)}}};b([document,window]).bind("resize",function(){})})(jQuery);
(function(i){var p=function(a){return a.replace(/^\/\//,"").replace(/[\/\.]/g,"_")},B=1,e,q,r,n=function(a){return a&&i.isFunction(a.always)},C=function(a){var b=[];if(n(a))return[a];else for(var c in a)n(a[c])&&b.push(a[c]);return b},v=function(a){return i.isArray(a)&&a.length===3&&a[1]==="success"?a[0]:a};e=i.View=function(a,b,c,d){if(typeof c==="function"){d=c;c=undefined}var f=C(b);if(f.length){var g=i.Deferred();f.push(r(a,true));i.when.apply(i,f).then(function(j){var k=i.makeArray(arguments),
l=k.pop()[0];if(n(b))b=v(j);else for(var m in b)if(n(b[m]))b[m]=v(k.shift());k=l(b,c);g.resolve(k);d&&d(k)});return g.promise()}else{var h;f=typeof d==="function";g=r(a,f);if(f){h=g;g.done(function(j){d(j(b,c))})}else g.done(function(j){h=j(b,c)});return h}};q=function(a,b){if(!a.match(/[^\s]/))throw"$.View ERROR: There is no template or an empty template at "+b;};r=function(a,b){return i.ajax({url:a,dataType:"view",async:b})};i.ajaxTransport("view",function(a,b){a=b.url;var c=a.match(/\.[\w\d]+$/),
d,f,g,h=a,j,k=function(l){l=d.renderer(g,l);if(e.cache)e.cached[g]=l;return{view:l}};if(f=document.getElementById(a))c=f.type.match(/\/[\d\w]+$/)[0].replace(/^\//,".");if(!c){c=e.ext;h+=e.ext}g=p(h);if(h.match(/^\/\//))h=typeof steal==="undefined"?"/"+h.substr(2):steal.root.mapJoin(h.substr(2));d=e.types[c];return{send:function(l,m){if(e.cached[g])return m(200,"success",{view:e.cached[g]});else if(f)m(200,"success",k(f.innerHTML));else j=i.ajax({async:b.async,url:h,dataType:"text",error:function(){q("",
h);m(404)},success:function(w){q(w,h);m(200,"success",k(w))}})},abort:function(){j&&j.abort()}}});i.extend(e,{hookups:{},hookup:function(a){var b=++B;e.hookups[b]=a;return b},cached:{},cache:true,register:function(a){this.types["."+a.suffix]=a;window.steal&&steal.type(a.suffix+" view js",function(b,c,d){c=e.types["."+b.type];var f=p(b.rootSrc);b.text=c.script(f,b.text);d()})},types:{},ext:".ejs",registerScript:function(a,b,c){return"$.View.preload('"+b+"',"+e.types["."+a].script(b,c)+");"},preload:function(a,
b){e.cached[a]=function(c,d){return b.call(c,c,d)}}});window.steal&&steal.type("view js",function(a,b,c){b=e.types["."+a.type];var d=p(a.rootSrc);a.text="steal('"+(b.plugin||"jquery/view/"+a.type)+"').then(function($){$.View.preload('"+d+"',"+a.text+");\n})";c()});var x,o,y,z,A,s,t;x=function(a){var b=i.fn[a];i.fn[a]=function(){var c=i.makeArray(arguments),d,f,g=this;if(n(c[0])){c[0].done(function(h){o.call(g,[h],b)});return this}else if(y(c)){if(d=A(c)){f=c[d];c[d]=function(h){o.call(g,[h],b);f.call(g,
h)};e.apply(e,c);return this}c=e.apply(e,c);if(n(c)){c.done(function(h){o.call(g,[h],b)});return this}else c=[c]}return o.call(this,c,b)}};o=function(a,b){var c;for(var d in e.hookups)break;if(d&&a[0]&&z(a[0])){c=e.hookups;e.hookups={};a[0]=i(a[0])}b=b.apply(this,a);c&&s(a[0],c);return b};y=function(a){var b=typeof a[1];return typeof a[0]=="string"&&(b=="object"||b=="function")&&!a[1].nodeType&&!a[1].jquery};z=function(a){if(a.jquery||a.nodeType===1)return true;else if(typeof a==="string"){a=i.trim(a);
return a.substr(0,1)==="<"&&a.substr(a.length-1,1)===">"&&a.length>=3}else return false};A=function(a){return typeof a[3]==="function"?3:typeof a[2]==="function"&&2};s=function(a,b){var c,d=0,f,g;a=a.filter(function(){return this.nodeType!=3});a=a.add("[data-view-id]",a);for(c=a.length;d<c;d++)if(a[d].getAttribute&&(f=a[d].getAttribute("data-view-id"))&&(g=b[f])){g(a[d],f);delete b[f];a[d].removeAttribute("data-view-id")}i.extend(e.hookups,b)};i.fn.hookup=function(){var a=e.hookups;e.hookups={};s(this,
a);return this};t=["prepend","append","after","before","text","html","replaceWith","val"];for(var u=0;u<t.length;u++)x(t[u])})(jQuery);
(function(f){f.String.rsplit=function(a,e){for(var b=e.exec(a),c=[],d;b!==null;){d=b.index;if(d!==0){c.push(a.substring(0,d));a=a.slice(d)}c.push(b[0]);a=a.slice(b[0].length);b=e.exec(a)}a!==""&&c.push(a);return c}})(jQuery);
(function(h){var q=function(a){eval(a)},r=function(a){return a.substr(0,a.length-1)},m=h.String.rsplit,k=h.extend,s=h.isArray,n=function(a){return a.replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/"/g,'\\"').replace(/\t/g,"\\t")},t=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&#34;").replace(/'/g,"&#39;")},f=function(a){if(this.constructor!=f){var b=new f(a);return function(c,e){return b.render(c,e)}}if(typeof a=="function"){this.template=
{};this.template.process=a}else{k(this,f.options,a);this.template=u(this.text,this.type,this.name)}};h.EJS=f;f.prototype={constructor:f,render:function(a,b){a=a||{};this._extra_helpers=b;b=new f.Helpers(a,b||{});return this.template.process.call(a,a,b)}};f.text=function(a){if(typeof a=="string")return a;if(a===null||a===undefined)return"";var b=a.hookup&&function(c,e){a.hookup.call(a,c,e)}||typeof a=="function"&&a||s(a)&&function(c,e){for(var d=0;d<a.length;d++)a[d].hookup?a[d].hookup(c,e):a[d](c,
e)};if(b)return"data-view-id='"+h.View.hookup(b)+"'";return a.toString?a.toString():""};f.clean=function(a){return typeof a=="string"?t(a):typeof a=="number"?a:f.text(a)};var o=function(a,b,c){b=m(b,/\n/);for(var e=0;e<b.length;e++)v(a,b[e],c)},v=function(a,b,c){a.lines++;b=m(b,a.splitter);for(var e,d=0;d<b.length;d++){e=b[d];e!==null&&c(e,a)}},w=function(a,b){var c={};k(c,{left:a+"%",right:"%"+b,dLeft:a+"%%",dRight:"%%"+b,eeLeft:a+"%==",eLeft:a+"%=",cmnt:a+"%#",scan:o,lines:0});c.splitter=new RegExp("("+
[c.dLeft,c.dRight,c.eeLeft,c.eLeft,c.cmnt,c.left,c.right+"\n",c.right,"\n"].join(")|(").replace(/\[/g,"\\[").replace(/\]/g,"\\]")+")");return c},u=function(a,b,c){a=a.replace(/\r\n/g,"\n").replace(/\r/g,"\n");b=b||"<";var e=new f.Buffer(["var ___v1ew = [];"],[]),d="",p=function(i){e.push("___v1ew.push(",'"',n(i),'");')},j=null,l=function(){d=""};o(w(b,b==="["?"]":">"),a||"",function(i,g){if(j===null)switch(i){case "\n":d+="\n";p(d);e.cr();l();break;case g.left:case g.eLeft:case g.eeLeft:case g.cmnt:j=
i;d.length>0&&p(d);l();break;case g.dLeft:d+=g.left;break;default:d+=i;break}else switch(i){case g.right:switch(j){case g.left:if(d[d.length-1]=="\n"){d=r(d);e.push(d,";");e.cr()}else e.push(d,";");break;case g.eLeft:e.push("___v1ew.push(","(jQuery.EJS.clean(",d,")));");break;case g.eeLeft:e.push("___v1ew.push(","(jQuery.EJS.text(",d,")));");break}j=null;l();break;case g.dRight:d+=g.right;break;default:d+=i;break}});d.length>0&&e.push("___v1ew.push(",'"',n(d)+'");');a={out:"try { with(_VIEW) { with (_CONTEXT) {"+
e.close()+" return ___v1ew.join('');}}}catch(e){e.lineNumber=null;throw e;}"};q.call(a,"this.process = (function(_CONTEXT,_VIEW){"+a.out+"});\r\n//@ sourceURL="+c+".js");return a};f.Buffer=function(a,b){this.line=[];this.script=[];this.post=b;this.push.apply(this,a)};f.Buffer.prototype={push:function(){this.line.push.apply(this.line,arguments)},cr:function(){this.script.push(this.line.join(""),"\n");this.line=[]},close:function(){if(this.line.length>0){this.script.push(this.line.join(""));this.line=
[]}this.post.length&&this.push.apply(this,this.post);this.script.push(";");return this.script.join("")}};f.options={type:"<",ext:".ejs"};f.Helpers=function(a,b){this._data=a;this._extras=b;k(this,b)};f.Helpers.prototype={plugin:function(){var a=h.makeArray(arguments),b=a.shift();return function(c){c=h(c);c[b].apply(c,a)}},view:function(a,b,c){c=c||this._extras;b=b||this._data;return h.View(a,b,c)}};h.View.register({suffix:"ejs",script:function(a,b){return"jQuery.EJS(function(_CONTEXT,_VIEW) { "+(new f({text:b,
name:a})).template.out+" })"},renderer:function(a,b){var c=new f({text:b,name:a});return function(e,d){return c.render.call(c,e,d)}}})})(jQuery);
(function(){function r(a,b,d,c){c={data:c||(b?b.data:{}),_wrap:b?b._wrap:null,tmpl:null,parent:b||null,nodes:[],calls:H,nest:I,wrap:J,html:K,update:L};a&&jQuery.extend(c,a,{nodes:[],parent:b});if(d){c.tmpl=d;c._ctnt=c._ctnt||c.tmpl(jQuery,c);c.key=++s;(x.length?t:l)[s]=c}return c}function u(a,b,d){var c;d=d?jQuery.map(d,function(f){return typeof f==="string"?a.key?f.replace(/(<\w+)(?=[\s>])(?![^>]*_tmplitem)([^>]*)/g,"$1 "+p+'="'+a.key+'" $2'):f:u(f,a,f._ctnt)}):a;if(b)return d;d=d.join("");d.replace(/^\s*([^<\s][^<]*)?(<[\w\W]+>)([^>]*[^>\s])?\s*$/,
function(f,e,g,i){c=jQuery(g).get();B(c);if(e)c=y(e).concat(c);if(i)c=c.concat(y(i))});return c?c:y(d)}function y(a){var b=document.createElement("div");b.innerHTML=a;return jQuery.makeArray(b.childNodes)}function C(a){return new Function("jQuery","$item","var $=jQuery,call,_=[],$data=$item.data;with($data){_.push('"+jQuery.trim(a).replace(/([\\'])/g,"\\$1").replace(/[\r\t\n]/g," ").replace(/\$\{([^\}]*)\}/g,"{{= $1}}").replace(/\{\{(\/?)(\w+|.)(?:\(((?:[^\}]|\}(?!\}))*?)?\))?(?:\s+(.*?)?)?(\(((?:[^\}]|\}(?!\}))*?)\))?\s*\}\}/g,
function(b,d,c,f,e,g,i){b=jQuery.tmpl.tag[c];if(!b)throw"Template command not found: "+c;c=b._default||[];if(g&&!/\w$/.test(e)){e+=g;g=""}if(e){e=z(e);i=i?","+z(i)+")":g?")":"";i=g?e.indexOf(".")>-1?e+g:"("+e+").call($item"+i:e;g=g?i:"(typeof("+e+")==='function'?("+e+").call($item):("+e+"))"}else g=i=c.$1||"null";f=z(f);return"');"+b[d?"close":"open"].split("$notnull_1").join(e?"typeof("+e+")!=='undefined' && ("+e+")!=null":"true").split("$1a").join(g).split("$1").join(i).split("$2").join(f?f.replace(/\s*([^\(]+)\s*(\((.*?)\))?/g,
function(o,m,v,k){return(k=k?","+k+")":v?")":"")?"("+m+").call($item"+k:o}):c.$2||"")+"_.push('"})+"');}return _;")}function D(a,b){a._wrap=u(a,true,jQuery.isArray(b)?b:[E.test(b)?b:jQuery(b).html()]).join("")}function z(a){return a?a.replace(/\\'/g,"'").replace(/\\\\/g,"\\"):null}function M(a){var b=document.createElement("div");b.appendChild(a.cloneNode(true));return b.innerHTML}function B(a){function b(m){function v(A){A+=d;h=e[A]=e[A]||r(h,l[h.parent.key+d]||h.parent,null,true)}var k,j=m,h,q;
if(q=m.getAttribute(p)){for(;j.parentNode&&(j=j.parentNode).nodeType===1&&!(k=j.getAttribute(p)););if(k!==q){j=j.parentNode?j.nodeType===11?0:j.getAttribute(p)||0:0;if(!(h=l[q])){h=t[q];h=r(h,l[j]||t[j],null,true);h.key=++s;l[s]=h}n&&v(q)}m.removeAttribute(p)}else if(n&&(h=jQuery.data(m,"tmplItem"))){v(h.key);l[h.key]=h;j=(j=jQuery.data(m.parentNode,"tmplItem"))?j.key:0}if(h){for(k=h;k&&k.key!=j;){k.nodes.push(m);k=k.parent}delete h._ctnt;delete h._wrap;jQuery.data(m,"tmplItem",h)}}var d="_"+n,c,
f,e={},g,i,o;g=0;for(i=a.length;g<i;g++)if((c=a[g]).nodeType===1){f=c.getElementsByTagName("*");for(o=f.length-1;o>=0;o--)b(f[o]);b(c)}}function H(a,b,d,c){if(!a)return x.pop();x.push({_:a,tmpl:b,item:this,data:d,options:c})}function I(a,b,d){return jQuery.tmpl(jQuery.template(a),b,d,this)}function J(a,b){var d=a.options||{};d.wrapped=b;return jQuery.tmpl(jQuery.template(a.tmpl),a.data,d,a.item)}function K(a,b){var d=this._wrap;return jQuery.map(jQuery(jQuery.isArray(d)?d.join(""):d).filter(a||"*"),
function(c){return b?c.innerText||c.textContent:c.outerHTML||M(c)})}function L(){var a=this.nodes;jQuery.tmpl(null,null,null,this).insertBefore(a[0]);jQuery(a).remove()}var F=jQuery.fn.domManip,p="_tmplitem",E=/^[^<]*(<[\w\W]+>)[^>]*$|\{\{\! /,l={},t={},w,G={key:0,data:{}},s=0,n=0,x=[];jQuery.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){jQuery.fn[a]=function(d){var c=[];d=jQuery(d);var f,e,g;f=this.length===1&&this[0].parentNode;
w=l||{};if(f&&f.nodeType===11&&f.childNodes.length===1&&d.length===1){d[b](this[0]);c=this}else{e=0;for(g=d.length;e<g;e++){n=e;f=(e>0?this.clone(true):this).get();jQuery.fn[b].apply(jQuery(d[e]),f);c=c.concat(f)}n=0;c=this.pushStack(c,a,d.selector)}d=w;w=null;jQuery.tmpl.complete(d);return c}});jQuery.fn.extend({tmpl:function(a,b,d){return jQuery.tmpl(this[0],a,b,d)},tmplItem:function(){return jQuery.tmplItem(this[0])},template:function(a){return jQuery.template(a,this[0])},domManip:function(a,b,
d){if(a[0]&&a[0].nodeType){for(var c=jQuery.makeArray(arguments),f=a.length,e=0,g;e<f&&!(g=jQuery.data(a[e++],"tmplItem")););if(f>1)c[0]=[jQuery.makeArray(a)];if(g&&n)c[2]=function(i){jQuery.tmpl.afterManip(this,i,d)};F.apply(this,c)}else F.apply(this,arguments);n=0;w||jQuery.tmpl.complete(l);return this}});jQuery.extend({tmpl:function(a,b,d,c){var f=!c;if(f){c=G;a=jQuery.template[a]||jQuery.template(null,a);t={}}else if(!a){a=c.tmpl;l[c.key]=c;c.nodes=[];c.wrapped&&D(c,c.wrapped);return jQuery(u(c,
null,c.tmpl(jQuery,c)))}if(!a)return[];if(typeof b==="function")b=b.call(c||{});d&&d.wrapped&&D(d,d.wrapped);b=jQuery.isArray(b)?jQuery.map(b,function(e){return e?r(d,c,a,e):null}):[r(d,c,a,b)];return f?jQuery(u(c,null,b)):b},tmplItem:function(a){var b;if(a instanceof jQuery)a=a[0];for(;a&&a.nodeType===1&&!(b=jQuery.data(a,"tmplItem"))&&(a=a.parentNode););return b||G},template:function(a,b){if(b){if(typeof b==="string")b=C(b);else if(b instanceof jQuery)b=b[0]||{};if(b.nodeType)b=jQuery.data(b,"tmpl")||
jQuery.data(b,"tmpl",C(b.innerHTML));return typeof a==="string"?(jQuery.template[a]=b):b}return a?typeof a!=="string"?jQuery.template(null,a):jQuery.template[a]||jQuery.template(null,E.test(a)?a:jQuery(a)):null},encode:function(a){return(""+a).split("<").join("&lt;").split(">").join("&gt;").split('"').join("&#34;").split("'").join("&#39;")}});jQuery.extend(jQuery.tmpl,{tag:{tmpl:{_default:{$2:"null"},open:"if($notnull_1){_=_.concat($item.nest($1,$2));}"},wrap:{_default:{$2:"null"},open:"$item.calls(_,$1,$2);_=[];",
close:"call=$item.calls();_=call._.concat($item.wrap(call,_));"},each:{_default:{$2:"$index, $value"},open:"if($notnull_1){$.each($1a,function($2){with(this){",close:"}});}"},"if":{open:"if(($notnull_1) && $1a){",close:"}"},"else":{_default:{$1:"true"},open:"}else if(($notnull_1) && $1a){"},html:{open:"if($notnull_1){_.push($1a);}"},"=":{_default:{$1:"$data"},open:"if($notnull_1){_.push($.encode($1a));}"},"!":{open:""}},complete:function(){l={}},afterManip:function(a,b,d){var c=b.nodeType===11?jQuery.makeArray(b.childNodes):
b.nodeType===1?[b]:[];d.call(a,b);B(c);n++}});$.View.register({suffix:"tmpl",renderer:function(a,b){var d=$.template(null,b);return function(c){return d.call($,$,{data:c}).join("")}},script:function(a,b){return"function(data){return ("+$.template(null,b)+").call(jQuery, jQuery, {data: data}).join(''); }"}});jQuery.View.ext=".tmpl"})(jQuery);
